/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/profile_fields/api/v1/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List field definitions
         * @description Return all profile field definitions ordered for admin management.
         *     This endpoint requires admin access
         */
        get: operations["field_definition_api-index"];
        put?: never;
        /**
         * Create field definition
         * @description Create a new profile field definition for the instance.
         *     This endpoint requires admin access
         */
        post: operations["field_definition_api-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update field definition
         * @description Update a profile field definition without changing its immutable key.
         *     This endpoint requires admin access
         */
        put: operations["field_definition_api-update"];
        post?: never;
        /**
         * Delete field definition
         * @description Delete a profile field definition and return the removed record.
         *     This endpoint requires admin access
         */
        delete: operations["field_definition_api-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/users/{userUid}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored values for a user
         * @description Return all persisted profile field values for a specific user.
         *     This endpoint requires admin access
         */
        get: operations["field_value_admin_api-index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/users/{userUid}/values/{fieldDefinitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert a stored value for a user
         * @description Create or update a profile field value for a specific user as an administrator.
         *     This endpoint requires admin access
         */
        put: operations["field_value_admin_api-upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/users/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lookup a user by a key profile field value
         * @description Resolve a Nextcloud user from an exact profile field match, then return the user's stored profile fields keyed by field key. This is intended for ETL or payroll-style integrations that know one authoritative identifier such as CPF and need the rest of the cooperative data.
         *     This endpoint requires admin access
         */
        post: operations["field_value_admin_api-lookup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users by one profile field filter
         * @description Return a paginated list of users that match one explicit profile field filter. The response includes only the field/value pair that produced the match, not the full profile.
         *     This endpoint requires admin access
         */
        get: operations["field_value_admin_api-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/me/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user-visible fields for the authenticated user
         * @description Return active profile fields visible to the authenticated user, together with any current stored value and whether the user can edit the value directly.
         */
        get: operations["field_value_api-index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/me/values/{fieldDefinitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert the authenticated user's value for an editable field
         * @description Create or update the current user's value for a field that allows self-service editing.
         */
        put: operations["field_value_api-upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/me/values/{fieldDefinitionId}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the visibility of the authenticated user's stored value
         * @description Change only the visibility of an already stored field value owned by the authenticated user.
         */
        put: operations["field_value_api-update-visibility"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Definition: {
            /** Format: int64 */
            id: number;
            field_key: string;
            label: string;
            type: components["schemas"]["Type"];
            edit_policy: components["schemas"]["EditPolicy"];
            exposure_policy: components["schemas"]["ExposurePolicy"];
            /** Format: int64 */
            sort_order: number;
            active: boolean;
            options: string[] | null;
            created_at: string;
            updated_at: string;
        };
        DefinitionInput: {
            field_key?: string;
            label?: string;
            type?: string;
            edit_policy?: components["schemas"]["EditPolicy"];
            exposure_policy?: components["schemas"]["ExposurePolicy"];
            /** Format: int64 */
            sort_order?: number;
            active?: boolean;
            options?: string[];
        };
        /** @enum {string} */
        EditPolicy: "admins" | "users";
        EditableField: {
            definition: components["schemas"]["Definition"];
            value: components["schemas"]["ValueRecord"];
            can_edit: boolean;
        };
        /** @enum {string} */
        ExposurePolicy: "hidden" | "private" | "users" | "public";
        LookupField: {
            definition: components["schemas"]["Definition"];
            value: components["schemas"]["ValueRecord"];
        };
        LookupResult: {
            user_uid: string;
            lookup_field_key: string;
            fields: {
                [key: string]: components["schemas"]["LookupField"];
            };
        };
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        SearchItem: {
            user_uid: string;
            display_name: string;
            fields: {
                [key: string]: components["schemas"]["LookupField"];
            };
        };
        SearchResult: {
            items: components["schemas"]["SearchItem"][];
            pagination: {
                /** Format: int64 */
                limit: number;
                /** Format: int64 */
                offset: number;
                /** Format: int64 */
                total: number;
            };
        };
        /** @enum {string} */
        Type: "text" | "number" | "boolean" | "date" | "url" | "select" | "multiselect";
        ValuePayload: {
            value: Record<string, never>;
        };
        ValueRecord: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            field_definition_id: number;
            user_uid: string;
            value: components["schemas"]["ValuePayload"];
            current_visibility: components["schemas"]["Visibility"];
            updated_by_uid: string;
            updated_at: string;
        };
        /** @enum {string} */
        Visibility: "private" | "users" | "public";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "field_definition_api-index": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field definitions listed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Definition"][];
                        };
                    };
                };
            };
        };
    };
    "field_definition_api-create": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Immutable unique key of the field */
                    fieldKey: string;
                    /** @description Human-readable label shown in the UI */
                    label: string;
                    /** @description Value type accepted by the field */
                    type: string;
                    /**
                     * @description Whether values are managed by admins only or by users too
                     * @default users
                     */
                    editPolicy?: string;
                    /**
                     * @description Whether the field is hidden or which default visibility new values receive
                     * @default private
                     */
                    exposurePolicy?: string;
                    /**
                     * Format: int64
                     * @description Display order used in admin and profile forms
                     * @default 0
                     */
                    sortOrder?: number;
                    /**
                     * @description Whether the definition is currently active
                     * @default true
                     */
                    active?: boolean;
                    /**
                     * @description Allowed values for select fields (ignored for other types)
                     * @default []
                     */
                    options?: string[];
                };
            };
        };
        responses: {
            /** @description Field definition created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Definition"];
                        };
                    };
                };
            };
            /** @description Invalid field definition payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_definition_api-update": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description Identifier of the field definition */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Human-readable label shown in the UI */
                    label: string;
                    /** @description Value type accepted by the field */
                    type: string;
                    /**
                     * @description Whether values are managed by admins only or by users too
                     * @default users
                     */
                    editPolicy?: string;
                    /**
                     * @description Whether the field is hidden or which default visibility new values receive
                     * @default private
                     */
                    exposurePolicy?: string;
                    /**
                     * Format: int64
                     * @description Display order used in admin and profile forms
                     * @default 0
                     */
                    sortOrder?: number;
                    /**
                     * @description Whether the definition is currently active
                     * @default true
                     */
                    active?: boolean;
                    /**
                     * @description Allowed values for select fields (ignored for other types)
                     * @default []
                     */
                    options?: string[];
                };
            };
        };
        responses: {
            /** @description Field definition updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Definition"];
                        };
                    };
                };
            };
            /** @description Invalid field definition payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_definition_api-delete": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description Identifier of the field definition */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field definition deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["Definition"];
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_admin_api-index": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description User identifier whose profile field values should be listed */
                userUid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User field values listed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ValueRecord"][];
                        };
                    };
                };
            };
        };
    };
    "field_value_admin_api-upsert": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description User identifier that owns the profile field value */
                userUid: string;
                /** @description Identifier of the field definition */
                fieldDefinitionId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Value payload to persist */
                    value?: ({
                        value?: (string | number | boolean) | null;
                    } | string | number | boolean) | null;
                    /** @description Visibility to apply to the stored value */
                    currentVisibility?: string | null;
                };
            };
        };
        responses: {
            /** @description User field value stored successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ValueRecord"];
                        };
                    };
                };
            };
            /** @description Invalid field value payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated admin user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_admin_api-lookup": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Immutable key of the lookup field, such as cpf */
                    fieldKey: string;
                    /** @description Value payload to match exactly */
                    fieldValue?: ({
                        value?: (string | number | boolean) | null;
                    } | string | number | boolean) | null;
                };
            };
        };
        responses: {
            /** @description User lookup completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                user_uid: string;
                                lookup_field_key: string;
                                fields: {
                                    [key: string]: {
                                        definition: {
                                            [key: string]: Record<string, never>;
                                        };
                                        value: components["schemas"]["ValueRecord"];
                                    };
                                };
                            };
                        };
                    };
                };
            };
            /** @description Invalid lookup payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated admin user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Lookup field definition or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Multiple users match the lookup field value */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_admin_api-search": {
        parameters: {
            query: {
                /** @description Immutable key of the field to filter by */
                fieldKey: string;
                /** @description Explicit search operator, currently `eq` or `contains` */
                operator?: string;
                /** @description Value payload to compare against the stored field value */
                value?: string | null;
                /** @description Maximum number of users to return in the current page */
                limit?: number;
                /** @description Zero-based offset into the matched result set */
                offset?: number;
            };
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User search completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["SearchResult"];
                        };
                    };
                };
            };
            /** @description Invalid search filter or pagination values */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated admin user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Search field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_api-index": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Editable profile fields listed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["EditableField"][];
                        };
                    };
                };
            };
            /** @description Authenticated user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_api-upsert": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description Identifier of the field definition */
                fieldDefinitionId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Value payload to persist */
                    value?: ({
                        value?: (string | number | boolean) | null;
                    } | string | number | boolean) | null;
                    /** @description Visibility to apply to the stored value */
                    currentVisibility?: string | null;
                };
            };
        };
        responses: {
            /** @description User field value stored successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ValueRecord"];
                        };
                    };
                };
            };
            /** @description Invalid field value payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field cannot be edited by the user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_api-update-visibility": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description Identifier of the field definition */
                fieldDefinitionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Visibility to apply to the stored value */
                    currentVisibility: string;
                };
            };
        };
        responses: {
            /** @description Field visibility updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ValueRecord"];
                        };
                    };
                };
            };
            /** @description Invalid visibility payload or value missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field visibility cannot be changed by the user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
}
