/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ocs/v2.php/apps/profile_fields/api/v1/me/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user-visible fields for the authenticated user
         * @description Return active profile fields visible to the authenticated user, together with any current stored value and whether the user can edit the value directly.
         */
        get: operations["field_value_api-index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/me/values/{fieldDefinitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert the authenticated user's value for an editable field
         * @description Create or update the current user's value for a field that allows self-service editing.
         */
        put: operations["field_value_api-upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/profile_fields/api/v1/me/values/{fieldDefinitionId}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the visibility of the authenticated user's stored value
         * @description Change only the visibility of an already stored field value owned by the authenticated user.
         */
        put: operations["field_value_api-update-visibility"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Definition: {
            /** Format: int64 */
            id: number;
            field_key: string;
            label: string;
            type: components["schemas"]["Type"];
            admin_only: boolean;
            user_editable: boolean;
            user_visible: boolean;
            initial_visibility: components["schemas"]["Visibility"];
            /** Format: int64 */
            sort_order: number;
            active: boolean;
            created_at: string;
            updated_at: string;
        };
        EditableField: {
            definition: components["schemas"]["Definition"];
            value: components["schemas"]["ValueRecord"];
            can_edit: boolean;
        };
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
        /** @enum {string} */
        Type: "text" | "number";
        ValuePayload: {
            value: Record<string, never>;
        };
        ValueRecord: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            field_definition_id: number;
            user_uid: string;
            value: components["schemas"]["ValuePayload"];
            current_visibility: components["schemas"]["Visibility"];
            updated_by_uid: string;
            updated_at: string;
        };
        /** @enum {string} */
        Visibility: "private" | "users" | "public";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "field_value_api-index": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Editable profile fields listed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["EditableField"][];
                        };
                    };
                };
            };
            /** @description Authenticated user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_api-upsert": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description Identifier of the field definition */
                fieldDefinitionId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Value payload to persist */
                    value?: ({
                        value?: (string | number | boolean) | null;
                    } | string | number | boolean) | null;
                    /** @description Visibility to apply to the stored value */
                    currentVisibility?: string | null;
                };
            };
        };
        responses: {
            /** @description User field value stored successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ValueRecord"];
                        };
                    };
                };
            };
            /** @description Invalid field value payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field cannot be edited by the user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "field_value_api-update-visibility": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                /** @description Identifier of the field definition */
                fieldDefinitionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Visibility to apply to the stored value */
                    currentVisibility: string;
                };
            };
        };
        responses: {
            /** @description Field visibility updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: components["schemas"]["ValueRecord"];
                        };
                    };
                };
            };
            /** @description Invalid visibility payload or value missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Authenticated user is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field visibility cannot be changed by the user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Field definition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
}
