// SPDX-FileCopyrightText: 2026 LibreCode coop and LibreCode contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

export const pedroPotiPersona = {
	user: {
		id: 'pedro_poti_demo',
		password: 'PedroDemoPass123!',
		displayName: 'Pedro Poti',
		email: 'pedro.poti@example.net',
	},
	accountFields: [
		{ label: 'Pronouns', value: 'he/him' },
		{ label: 'Location', value: 'Massurepe, Paraiba' },
		{ label: 'Organisation', value: 'Potiguara people' },
		{ label: 'Role', value: 'Regedor of Paraiba' },
		{ label: 'Headline', value: 'Potiguara leader and Reformed ally in Dutch Brazil' },
		{ label: 'About', value: 'Potiguara leader from Paraiba who spent five years in the Netherlands, learned to read and write, embraced the Reformed faith, and later served as regedor for the Paraiba chamber.' },
	],
	showcaseFields: [
		{
			fieldKey: 'showcase_support_region',
			label: 'Territory',
			type: 'text',
			adminOnly: false,
			userEditable: true,
			userVisible: true,
			initialVisibility: 'users',
			sortOrder: 10,
			adminValue: { value: 'Recife administration', currentVisibility: 'users' },
			demoValue: { value: 'Captaincy of Paraiba', currentVisibility: 'users' },
		},
		{
			fieldKey: 'showcase_product_specialty',
			label: 'Core strength',
			type: 'text',
			adminOnly: false,
			userEditable: true,
			userVisible: true,
			initialVisibility: 'public',
			sortOrder: 20,
			adminValue: { value: 'Field coordination', currentVisibility: 'public' },
			demoValue: { value: 'Tupi correspondence', currentVisibility: 'public' },
		},
		{
			fieldKey: 'showcase_customer_segment',
			label: 'Community',
			type: 'text',
			adminOnly: false,
			userEditable: true,
			userVisible: true,
			initialVisibility: 'users',
			sortOrder: 30,
			adminValue: { value: 'Colonial administration', currentVisibility: 'users' },
			demoValue: { value: 'Potiguara communities', currentVisibility: 'users' },
		},
		{
			fieldKey: 'showcase_escalation_alias',
			label: 'Letter alias',
			type: 'text',
			adminOnly: false,
			userEditable: true,
			userVisible: true,
			initialVisibility: 'private',
			sortOrder: 40,
			adminValue: { value: 'recife-council-ledger', currentVisibility: 'private' },
			demoValue: { value: 'pedro-poti-tupi-letters', currentVisibility: 'private' },
		},
		{
			fieldKey: 'showcase_incident_role',
			label: 'Leadership role',
			type: 'text',
			adminOnly: false,
			userEditable: true,
			userVisible: true,
			initialVisibility: 'users',
			sortOrder: 50,
			adminValue: { value: 'Administrative overseer', currentVisibility: 'users' },
			demoValue: { value: 'Regedor of Paraiba', currentVisibility: 'users' },
		},
		{
			fieldKey: 'showcase_on_call_tier',
			label: 'Council rank',
			type: 'number',
			adminOnly: true,
			userEditable: false,
			userVisible: true,
			initialVisibility: 'private',
			sortOrder: 60,
			adminValue: { value: 2, currentVisibility: 'private' },
			demoValue: { value: 1, currentVisibility: 'private' },
		},
	],
}
